### ISSUE TITLE
MacOS Documentation

### ISSUE THREAD

**Issue by mwilliams** [TheTechnobear/Orac#1]
Would love to see any minimal documentation running ORAC on MacOS with a MIDI controller and chaining Organelle patches in the same manner as you can on the Organelle hardware with with everything entirely in MacOS - is it even possible (to get the display output especially somewhere)?
 
I've gotten single patches running just fine with `mother-desktop.pd`, but trying to parse through ORAC (and a totally new to Pure Data).  Amazing work btw!  This might be the project that gets me to grab an Organelle!

**Comment by TheTechnobear** [comment]
orac 1.1 will be able to run on macOS,
but  (at least initially) this is only really designed for development purposes, 
as I think there are many alternatives to Orac on desktops.
… my personal direction for Orac, is more toward headless (on minimal) setups like the Organelle, rPI and Bela.

that said, i will detail the basics of how to run the macOS version when orac 1.1 is completed, and released

**Comment by mwilliams** [comment]
Awesome, thanks! I’ve got an OP-1 I was going to use as a MIDI controller
which will get me the four encoders and with midi learn, the modifier key
on the organelle (if I understand the hardware correctly?).

Anyway, thanks for the response! Pretty stoked about this project and if
I’m able to contribute anything back, I’d be happy to!

**Comment by TheTechnobear** [comment]
hmm, kind of , and kind of not :) 

midi learn is for parameter mapping, its not aimed at emulating an organelle, which is a different thing...the reason is, even if you could emulate the pots, you'd still need to have the display.

rather, the idea with midi learn, is that you want to learn the particular parameters (or as many as you have controls for), so that you can change them without any reference to the particular module or page selected...

anyway, this will make more sense once i release the 'remote control' app, where you'll see how you can control Orac without an Organelle or Push2.

but important thing here, is Orac is Orac, which happens to have modules from the Organelle, its not trying to be an Organelle emulator :)

**Comment by TheTechnobear** [comment]
with Orac 2.0 this is now possible, 
as you can use remote control or the Push2 interface 

note: I dont plan to distribute Orac on the mac though
this means it has to be compiled here.
thats easy :
./scripts/create_macos.sh

and it might be that the mec externals are out of date, as this is built separately and copied across.
(though Ive just updated so are correct at the moment) 

also I don't distribute the externals for various synths (except my MI ones) so you may need to pull those down yourself.
