### ISSUE TITLE
Orac package manger

### ISSUE THREAD

**Issue by dr-kd** [TheTechnobear/Orac#14]
Have you had any thoughts on how a package manager for orac would be put together?  Is this of interest.  I'm thinking something like apt-get, cpan, pip.  Is this something that would be of interest.  I can ask around to see how far you can get from off the shelf components.

**Comment by TheTechnobear** [comment]
Im not really sure I see what value a package manager would add...

the issue is many that contribute 3rd partly modules - are 'hobby;  developers, but just know some pd.
adding more technology would potentially exclude these users from contributio.
so I would not want to include something that raised the 'technical skills' requirements for producing modules.
