### ISSUE TITLE
Seq2 not working on Raspberry Pi

### ISSUE THREAD

**Issue by NothanUmber** [TheTechnobear/Orac#5]
When switching to Seq2 from another module the parameters stay the same as for the previous module (when using the Pd OscClient). When moving a parameter no values are changed.
In /var/log/daemon.log there is an error message: 
error: /home/patch/data/orac/presets/Init/a1-sequence.txt: can't open

Tested with Orac2 Beta 2 on Patchbox OS

**Comment by TheTechnobear** [comment]
there are no parameters for seq2 - so it sounds like its just not clearing the labels.
its likely a small bug in the PD osc client.
(does it do the same on lemur, if so might be an issue on oscdisplay, but again a minor bug not clearing the titles)

that error is not an error, its as it says - its tries to load an existing sequence, but you don't have one because the the init preset doesn't have one saved for that slot (or any other slot)

**Comment by NothanUmber** [comment]
ah, ok :)

**Comment by NothanUmber** [comment]
yepp, same effect when returning from any module to the Empty module, seems to be a an OSCClient bug.
