### ISSUE TITLE
trying to run in MacOs, a bit lost...

### ISSUE THREAD

**Issue by moebiussurfing** [TheTechnobear/Orac#7]
hey @TheTechnobear, thanks a lot for doing and sharing all this thing.

I discovered Organelle some weeks ago and I am trying to make some standalone openFrameworks based MacOs app. I have some features working decently, also some oled drawing, but dirty yet. So I am curious to check your Orac system because looks promising all the modular thing, preset and midi cc system. :)

I ran the /Orac/macOS/run.sh script and it's working and it sounds in the background, without gui as expected.

Then I opened Orac/OscClients/pd/main.pd to feed/receive from the background app, but can't figure out how to setup right for control/display the Orac app.

I changed the host name 'edit hostname here->' in the main.pd patch from 'organelle' to 'localhost', clicked bang etc..
Then I edited /Orac/pkg/macos/MEC/osckontrol.json trying (?) to fit the same pd port (changed 6000 to  6101)
```
{
    "mec"  :  {
        "oscdisplay"  :  {
            "listen port" : 6100
        },

        "kontrol"  :  {
            "listen port" : 6101
        }
    },
```
But I am not sure if this is what we need to do or not... If you can point to some basic tips I will be appreciated.
If I don't understand badly, the pd osc client patch should send to the background (sounding) app to control menus and settings, and also the patch will act as 'the oled screen'? 

it's Orac/OscClients/pd/main.pd i kind of mother-desktop (organelle like) app? 

cheers

**Comment by moebiussurfing** [comment]
ps1: I am not sure I must run  /Orac/pkg/macos/MEC/mec-app or if it's already running in the background.

ps2: when opening /OracRemoteClients/pd/main.pd I am getting this into the pd console:
```
LISTEN:: listen 6101
connecting to port 6100
SEND:: connect 127.0.0.1 6100
recv: Connection refused (61)
```
Nothing happens to sound when moving sliders and can't jump into browsing when clicking gui bangs..

**Comment by TheTechnobear** [comment]
I should say upfront I don't really support Orac on macOS.
it only really exists as i use it as a development platform, its developers rather than something I would expect end users to use.

the reason i mention this, is that it may require you to 'hack' certain things together to make it work, 
and its possible at times, certain things might be out of date etc.
(also some modules won't work, as ive not compiled the externals they need for macOS) 


(there are so many options on macOS/windows, i don't really see Orac offering much new to end users)

----

that all said...
you should not need to edit any files, as far as i know the ones in the repo are correct.

the way it works is PD and MEC also communicate via OSC/ udp ports, 
and then the osc client (pd) talks to MEC via OSC/udp

in this particular case....
the osc client pd, connects to the MEC port 6100 (what you see as oscdisplay), and the client listens on 6101... MEC knows this because its told this when it connects.

the ports you are messing about with are for the MEC<->PD orac, so that wont work, and will break that link ;) 

----

so you'd need to set this back to how it was, and then look at the logs to see whats going.

**Comment by TheTechnobear** [comment]
the fact you are getting 
[code]
connecting to port 6100
SEND:: connect 127.0.0.1 6100
recv: Connection refused (61)
[/code]

indicates to me either mec is not running, or not using the right config file.

the run.sh runs mec, but if your debugging issues, id recommend you start it manually, so you can see error messages etc.
(also start pd/orac manually in another window)

**Comment by moebiussurfing** [comment]
ok. thanks. now it's working
I ran mec alone like you said, I had an error and 'brew install cairo' fixed my problem.
then I ran the run.sh again and now the browsing it's working, and also sliders affects the sound.
